# Site settings
title: BORDELTABERNCALE
email: robertphoenix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'll think up something later, yah.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bordeltabernacle.github.io" # the base hostname & protocol for your site
twitter_username: brdltbrncle
github_username:  bordeltabernacle

# Build settings
markdown: GFM
