# Site settings
title: Bordeltabernacle
email: robertphoenix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I used to be an artist. Now I write code.
  I still read short stories and listen to Blues music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bordeltabernacle.github.io" # the base hostname & protocol for your site
twitter_username: brdltbrncle
github_username:  bordeltabernacle
# Post settings
excerpt_separator: <!--more-->
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
